### ISSUE TITLE
Error running `make install-libraries`

### ISSUE THREAD

**Issue by asr** [jonaprieto/athena#28]
```
$ make install-libraries
===================================================================
===== Downloading Agda Standard Library v2.5.2.20170816    ========
===================================================================
warning: Could not find remote branch v2.5.2.20170816  to clone.
fatal: Remote branch v2.5.2.20170816  not found in upstream origin
```
Note that `v2.5.2.20170816` is not a branch but a tag.

You can use version 0.14 available in the Agda wiki (due to a problem with Agda mailing list server this version hasn't been announced yet).

**Comment by jonaprieto** [comment]
> Note that v2.5.2.20170816 is not a branch but a tag.

It's message generated by git. 

The reason:

> --branch can also take tags and detaches the HEAD at that commit in the resulting repository.

> You can use version 0.14 available in the Agda wiki

Thanks!, I'll update it in brevity.

**Comment by asr** [comment]
Note that you support two versions of Agda so you need to support two versions of the standard library...

I suggest to remove the support for Agda 2.5.2.

**Comment by jonaprieto** [comment]
> I suggest to remove the support for Agda 2.5.2.

Sounds better.

**Comment by asr** [comment]
Which commit fixed the issue?

**Comment by jonaprieto** [comment]
Sorry. cc96ba69883b59d760fb63a7ebdd80b255c4b4b2
