### ISSUE TITLE
Bad perfomance

### ISSUE THREAD

**Issue by asr** [jonaprieto/athena#31]
Which is your output of running the following command:

```
$ time agda test/prop-pack/problems/prop-metis/prop-21.agda
```
In my case, after 4 hours of running

```
$ time agda -v20 test/prop-pack/problems/prop-metis/prop-21.agda
```

the process continued running (and `htop` didn't showed any significant change).

**Comment by jonaprieto** [comment]
I remember Agda type-checked the problem after two hours, but it was using a computer in the lab, not mine, something like yours at the office. I recently changed  `atp-conjunct` but no other changes significant. What computer are you using for the test?

**Comment by asr** [comment]
> What computer are you using for the test?

The computer of my office.

**Comment by asr** [comment]
> I recently changed `atp-conjunct` but no other changes significant.

In which commit did you make the change?

**Comment by jonaprieto** [comment]
In the lab, The type-check finished:

```
real    574m0.842s
user    571m39.728s
sys     1m10.404s

```

**Comment by jonaprieto** [comment]
> In which commit did you make the change?

https://github.com/jonaprieto/agda-metis/commit/df7dc1e8f89a287bdfa88553378d1e5a89fc1a3e

**Comment by asr** [comment]
> In the lab, The type-check finished:

Agda, Alex, GHC and Happy versions?

**Comment by asr** [comment]
Is the file in the OP type-checked on Travis?

**Comment by jonaprieto** [comment]
> Agda, Alex, GHC and Happy versions?

```
$ agda --version
Agda version 2.5.2.20170816
$ alex --version
Alex version 3.2.1, (c) 2003 Chris Dornan and Simon Marlow
$ happy --version
Happy Version 1.19.5 ...
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.2.1
```

**Comment by asr** [comment]
Is the file in the OP type-checked on Travis?

**Comment by jonaprieto** [comment]
No.  Because of the Timelimit and the restriction of time running in Travis.

**Comment by asr** [comment]
> In the lab, the type-check finished:
>```
>real    574m0.842s
>user    571m39.728s
>sys     1m10.404s
>```

I got very similar figures.

**Comment by jonaprieto** [comment]
Then, are you agree if we close it? It's taking a lot of time but definitely is not a loop.

**Comment by asr** [comment]
I agree that it is not a loop but we need to understand what is causing this behaviour. Agda? Athena? agda-metis? We'll talk about it in our meeting tomorrow.

**Comment by asr** [comment]
I got the same behaviour by using agda-metis on commit https://github.com/jonaprieto/agda-metis/commit/0dde861012256839b184fc5a493ff1fb263c27f9 (that is, I removed the commits https://github.com/jonaprieto/agda-metis/commit/e2469c993fe857ec98546db75408a7370a77f8f3, https://github.com/jonaprieto/agda-metis/commit/0730f85916924d10e4504ccad0cd7459b1b24671, https://github.com/jonaprieto/agda-metis/commit/df7dc1e8f89a287bdfa88553378d1e5a89fc1a3e, https://github.com/jonaprieto/agda-metis/commit/b7893ba38a4f362915befbb22004e0985c232468, https://github.com/jonaprieto/agda-metis/commit/2a7f3ab4a23d8796bf4ea1b4fb3e633f1c72fcda and https://github.com/jonaprieto/agda-metis/commit/f42201eac70b95adf297e5f4f00d3e8a1c2fdf81).

**Comment by jonaprieto** [comment]
Relvant to this issue is the commit that changes how is defined the resolve rule:
 jonaprietp/agda-metis@b3302f77c6e42106613b1552ecaeeac7a42879e4

The type-checking is faster for our collection of problems, on average of 3seg in my laptop,
could you please confirm @asr how is in your pc?

I tested with ghc-8.4.2 and agda-2.5.4.

**Comment by asr** [comment]
Why there is no a link associated to the above commit?

**Comment by asr** [comment]
When running `make check` I am getting `Just Nothing` in each file, e.g.

```
-------------------------------------------------------------------
===================================================================
================== Type-checking Agda files =======================
===================================================================

test/prop-pack/problems/basic/basic-01.agda
Just Nothing
-------------------------------------------------------------------
test/prop-pack/problems/basic/basic-02.agda
Just Nothing
-------------------------------------------------------------------
test/prop-pack/problems/basic/basic-03.agda
Just Nothing
...
```

Is this the expected output?

**Comment by jonaprieto** [comment]
Not at all, that's weird.
Please see in Travis the jobs finished. For instance, at the end of this link,
you see the expected output.

https://api.travis-ci.org/v3/job/396940487/log.txt

I'll think why you have that.
