### ISSUE TITLE
Agda and Agda standard library versions

### ISSUE THREAD

**Issue by asr** [jonaprieto/athena#62]
I'm using Agda 2.5.4. Following the instructions [here](https://github.com/jonaprieto/athena#installing-the-athena-tool) I run

```
make install-libraries
```

but the version installed of the standard library (version 0.14) isn't compatible with Agda 2.5.4.

**Comment by asr** [comment]
Thanks!

**Comment by jonaprieto** [comment]
I forgot to remove this variable `ATHENAOPTIONS ="--script"` in the makefile to print proofs using the script mode...

**Comment by asr** [comment]
?
