### ISSUE TITLE
Travis failing

### ISSUE THREAD

**Issue by jonaprieto** [jonaprieto/athena#8]
Andrés, @asr 

I forgot when you said something about using the standard library of Agda with Athena, it was to fix travis.

[Travis #76:](https://travis-ci.org/jonaprieto/athena/builds/220757333)
```
...
/basic-3.agda
/home/travis/agda-stdlib/src/Data/Empty.agda:13,5-5
/home/travis/agda-stdlib/src/Data/Empty.agda:13,5: Parse error
FOREIGN<ERROR>
 GHC data AgdaEmpty #-}
...

```
Was about installing Agda using cabal?

**Comment by asr** [comment]
If you install Agda via Cabal, you need the version of the standard library compatible with your version of Agda. See the compatibility list in http://wiki.portal.chalmers.se/agda/pmwiki.php?n=Libraries.StandardLibrary.

**Comment by jonaprieto** [comment]
Thank you Andrés, I solved it.

Btw, I added in the Makefile a target to install a specific version of that library.

```
agda-stdlib:
	@if [ ! -d lib/agda-stdlib ] ; \
	 then \
	 echo "===================================================================";\
	 echo "===== Downloading Agda standard library v0.13 (Agda 2.5.2) ========";\
	 echo "===================================================================";\
	 git config --global advice.detachedHead false && \
	 git clone -q --progress \
			-b 'v0.13' \
			--single-branch \
			https://github.com/agda/agda-stdlib.git \
			lib/agda-stdlib; \
	 echo "Installed agda-stdlib v0.13 in ${ATHENA_LIB}/agda-stdlib"; \
	 else \
		 echo "[!] agda-stdlib directory already exists"; \
	 fi;
```

6079044c34411a96991eca67d501f688a1e818f8
